version: '2.1'
services:
  web:
    container_name: node-app
    build: .
    ports:
      - 8080:8080
    links:
      - db
    volumes:
      - d:/projects/gitRepo/express-router:/express-router

  db:
    container_name: app-db
    image: mongo:3-xenial
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - .mongodb:/data/db
