version: '3'
services:
  web:
    container_name: node-app
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/home/app
    links:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017/players
  db:
    image: mongo:3-xenial
    container_name: db
